### ISSUE TITLE
[V2 controller bug] MIA MRIQC pipelines does not work with V2 controller

### ISSUE THREAD

**Issue by LStruber** [populse/mia_processes#10]
When using V2 controller, it is impossible to display the node controller neither of mia_processes.pipelines.preprocess.Anat_mriqc_pipeline nor of mia_processes.pipelines.preprocess.Bold_mriqc_pipeline, whereas it is working with controller V1. 

With V2 controller, after adding the brick in the pipeline manager, a left click on it makes MIA crash with the following standard output:

```
Traceback (most recent call last):
  File "/home/lucas/populse_dev/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1147, in displayNodeParameters
    self.pipelineEditorTabs.get_current_pipeline())
  File "/home/lucas/populse_dev/populse_mia/python/populse_mia/user_interface/pipeline_manager/node_controller.py", line 502, in display_parameters
    userlevel=userlevel)
  File "/casa/host/src/capsul/master/capsul/qt_gui/widgets/attributed_process_widget.py", line 168, in __init__
    user_data=user_data, userlevel=userlevel, select_controls=sel)
  File "/casa/host/build/python/soma/qt_gui/controller_widget.py", line 265, in __init__
    self._create_controls()
  File "/casa/host/build/python/soma/qt_gui/controller_widget.py", line 618, in _create_controls
    self.create_control(trait_name, trait)
  File "/casa/host/build/python/soma/qt_gui/controller_widget.py", line 672, in create_control
    layout, group)
  File "/casa/host/build/python/soma/qt_gui/controller_widget.py", line 808, in _create_control_in_layout
    trait, label_class, user_data=self.user_data)
  File "/casa/host/build/python/soma/qt_gui/controls/List_offscreen.py", line 192, in create_widget
    weak_proxy(parent), weak_proxy(frame), control_value)
  File "/casa/host/build/python/soma/qt_gui/controls/List_offscreen.py", line 236, in partial_view_widget
    max_items=widget.max_items, user_data=parent_frame.user_data)
  File "/casa/host/build/python/soma/qt_gui/controls/List.py", line 275, in create_widget
    user_data=user_data)
  File "/casa/host/build/python/soma/qt_gui/controller_widget.py", line 265, in __init__
    self._create_controls()
  File "/casa/host/build/python/soma/qt_gui/controller_widget.py", line 618, in _create_controls
    self.create_control(trait_name, trait)
  File "/casa/host/build/python/soma/qt_gui/controller_widget.py", line 672, in create_control
    layout, group)
  File "/casa/host/build/python/soma/qt_gui/controller_widget.py", line 808, in _create_control_in_layout
    trait, label_class, user_data=self.user_data)
  File "/casa/host/build/python/soma/qt_gui/controls/Compound.py", line 144, in create_widget
    CompoundControlWidget.create_compound_widget(widget)
  File "/casa/host/build/python/soma/qt_gui/controls/Compound.py", line 245, in create_compound_widget
    control_label.deleteLater()
AttributeError: 'NoneType' object has no attribute 'deleteLater'

Process finished with exit code 1
```

As the issue can be reproduced with Registration brick alone (crash with same standard output), not when left-clicking on it but when trying to modify for example transform parameters traits, I think this could be due to unsupported (by V2 controller) input traits of this brick. For example it has these inputs that could cause problem:
```
self.add_trait("transform_parameters",
                       List(Either(
                           Tuple(Float),
                           Tuple(Float, Float, Float),
                           Tuple(Float, Int, Int, Int),
                           Tuple(Float, Int, Float, Float, Float, Float),
                           Tuple(Float, Float, Float, Int),
                           Tuple(Float, Int, Int, Int, Int)),
                           default=Undefined,
                           output=False,
                           optional=False,
                           desc=transform_parameters_desc))

self.add_trait("metric",
                       List(Enum('CC',
                                 'MeanSquares',
                                 'Demon',
                                 'GC',
                                 'MI',
                                 'Mattes'),
                            default=Undefined,
                            output=False,
                            optional=False,
                            desc=metric_desc))
```

**Comment by denisri** [comment]
I have pushed a fix that avoids the crash. Now I'm not sure these parameters types are correctly displayed...

**Comment by servoz** [comment]
Thanks @denisri. I don't have in mind this issue Lucas had described. As he is now gone I'll have to dive back into it ASAP. I'm finishing my current work for installing and testing singularity container 5.5-6 and I'll come back to test it properly.

**Comment by LStruber** [comment]
I just tested with @denisri fix.
Now the node controller displays when using controller V2, although the values of the tuples (reg_transform_parameters in the image below) are not editable (while of course they were with controller V1):
![Capture](https://user-images.githubusercontent.com/86590799/167669357-7f2f2dc0-0755-415d-9f83-9999fe626c75.PNG)

**However**, when defining the input anat file from Filter button in the controller, MIA crashes (after clicking OK in the database popup window) with the following standard output
```

Traceback (most recent call last):
  File "/casa/host/build/python/soma/qt_gui/controls/File.py", line 249, in update_controller
    controller_widget.controller.protect_parameter(control_name)
  File "/casa/host/build/python/soma/controller/controller.py", line 515, in protect_parameter
    hidden=True))
  File "/home/lucas/casa_distro/casa-dev-5.1/usr/lib/python3/dist-packages/traits/has_traits.py", line 2791, in add_trait
    self.add_trait( name + '_items', handler.items_event() )
  File "/casa/host/src/capsul/master/capsul/pipeline/pipeline.py", line 325, in add_trait
    super(Pipeline, self).add_trait(name, trait)
  File "/casa/host/src/capsul/master/capsul/process/process.py", line 265, in add_trait
    super(Process, self).add_trait(name, trait)
  File "/casa/host/build/python/soma/controller/controller.py", line 333, in add_trait
    self.user_traits_changed = True
  File "/home/lucas/casa_distro/casa-dev-5.1/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 474, in __call__
    self.notify_listener( self, object, trait_name, old, new )
  File "/home/lucas/casa_distro/casa-dev-5.1/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 545, in _notify_method_listener
    listener )
  File "/home/lucas/casa_distro/casa-dev-5.1/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 526, in _dispatch_change_event
    handle_exception( object, trait_name, old, new )
  File "/home/lucas/casa_distro/casa-dev-5.1/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/home/lucas/casa_distro/casa-dev-5.1/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 614, in dispatch
    handler( *args )
  File "/casa/host/build/python/soma/qt_gui/controller_widget.py", line 561, in update_controls
    self.connect()
  File "/casa/host/build/python/soma/qt_gui/controller_widget.py", line 395, in connect
    self.update_controller_widget()
  File "/casa/host/build/python/soma/qt_gui/controller_widget.py", line 358, in update_controller_widget
    control_instance)
  File "/casa/host/build/python/soma/qt_gui/controls/List_offscreen.py", line 350, in update_controller_widget
    cls.disconnect(controller_widget, control_name, control_instance)
  File "/casa/host/build/python/soma/qt_gui/controls/List_offscreen.py", line 539, in disconnect
    inner_control_instance)
  File "/casa/host/build/python/soma/qt_gui/controls/Enum.py", line 289, in disconnect
    controller_hook) = control_instance._controller_connections
AttributeError: 'QComboBox' object has no attribute '_controller_connections'

Process finished with exit code 1
```

I won't have time to make changes in the code, but I still can test fixes and answer here ;)

**Comment by servoz** [comment]
The V2 controller GUI does not work correctly with all parameter types, this is a known issue (populse/populse_mia#192), but for MRIQC anat and func, tests carried out today indicate that this pipeline now works with the V2 GUI.
