### ISSUE TITLE
[iteration] brick Level1design 

### ISSUE THREAD

**Issue by manuegrx** [populse/mia_processes#46]
Issue to iterate a pipeline if level1design brick used. 

For example with the pipeline Bold_stat_cvr if we choose to iterate over smoother_func parameter: 

```
Traceback (most recent call last):
  File "/home/gourieuxe/.local/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 129, in validate
    value = Path(value)  # Use pathlib's validation
  File "/usr/lib/python3.8/pathlib.py", line 1042, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.8/pathlib.py", line 683, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.8/pathlib.py", line 667, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not _Undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gourieuxe/apps/sources_populse/populse_mia/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 3327, in update_scans_list
    new_pipeline = self.build_iterated_pipeline()
  File "/home/gourieuxe/apps/sources_populse/populse_mia/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 1108, in build_iterated_pipeline
    pipeline.add_link(
  File "/home/gourieuxe/apps/sources_populse/capsul/capsul/pipeline/pipeline.py", line 1066, in add_link
    dest_node.set_plug_value(dest_plug_name, value)
  File "/home/gourieuxe/apps/sources_populse/capsul/capsul/pipeline/pipeline_nodes.py", line 797, in set_plug_value
    self.process.set_parameter(plug_name, value, protected)
  File "/home/gourieuxe/apps/sources_populse/capsul/capsul/process/process.py", line 1067, in set_parameter
    setattr(self, name, value)
  File "/home/gourieuxe/.local/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 424, in validate
    value = super(MultiObject, self).validate(objekt, name, newvalue)
  File "/home/gourieuxe/.local/lib/python3.8/site-packages/traits/trait_types.py", line 2699, in validate
    return TraitListObject(self, object, name, value)
  File "/home/gourieuxe/.local/lib/python3.8/site-packages/traits/trait_list_object.py", line 582, in __init__
    super().__init__(
  File "/home/gourieuxe/.local/lib/python3.8/site-packages/traits/trait_list_object.py", line 213, in __init__
    super().__init__(self.item_validator(item) for item in iterable)
  File "/home/gourieuxe/.local/lib/python3.8/site-packages/traits/trait_list_object.py", line 213, in <genexpr>
    super().__init__(self.item_validator(item) for item in iterable)
  File "/home/gourieuxe/.local/lib/python3.8/site-packages/traits/trait_list_object.py", line 865, in _item_validator
    return trait_validator(object, self.name, value)
  File "/home/gourieuxe/.local/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/home/gourieuxe/.local/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 131, in validate
    self.error(objekt, name, str(value))
  File "/home/gourieuxe/.local/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: Each element of the 'sess_scans' trait of a Level1Design instance must be a pathlike object or string representing a file, but a value of '<undefined>' <class 'str'> was specified.
```

`sess_scans` is defined as follows:
```
        self.add_trait(
            "sess_scans",
            InputMultiPath(
                File(exists=True),
                usedefault=True,
                output=False,
                desc=sess_scans_desc,
            ),
        )
```

I will try some test tomorrow

**Comment by manuegrx** [comment]
This [commit](https://github.com/populse/mia_processes/commit/ac2acc4259d9866b322d6eb26a00cc32156b7845) fix the issue when using the iteration [via a regular iterative pipeline](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-a-regular-iterative-pipeline-without-use-of-the-iteration-table) with  `Files_to_List` brick to transform file to list for `sess_scans` parameter (because it is a List). 

However if I iterate [via a regular iterative pipeline](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-a-regular-iterative-pipeline-without-use-of-the-iteration-table)  using `ReduceNode`  brick (from Capsul) or if I iterate [via input filter brick/process](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-input-filter-brick-process) I have an issue with the `ReduceNode`brick.

As it seems to be an issue unrelated to level1design brick I open an other ticket https://github.com/populse/populse_mia/issues/309
